export const recipes = [
  {
    recipe_id: 1,
    recipe_name: "Spaghetti Carbonara",
    description: "A classic Italian pasta dish.",
    prep_time: "10 mins",
    cook_time: "15 mins",
    total_time: "25 mins",
    servings: 4,
    ingredients: [
      "Spaghetti",
      "Eggs",
      "Parmesan Cheese",
      "Bacon",
      "Black Pepper",
      "Salt",
    ],
    instructions: [
      "Boil the spaghetti in salted water until al dente.",
      "Fry the bacon until crispy.",
      "Beat eggs in a bowl and mix with grated Parmesan.",
      "Toss the spaghetti with the bacon and egg mixture off the heat.",
      "Season with black pepper and salt to taste.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["Italian", "Pasta", "Main Course"],
  },
  {
    recipe_id: 2,
    recipe_name: "Chicken Curry",
    description: "A flavorful Indian chicken curry.",
    prep_time: "20 mins",
    cook_time: "40 mins",
    total_time: "1 hour",
    servings: 4,
    ingredients: [
      "Chicken",
      "Onion",
      "Garlic",
      "Ginger",
      "Tomatoes",
      "Spices",
      "Coconut Milk",
    ],
    instructions: [
      "Fry onions, garlic, and ginger until golden.",
      "Add spices and fry for a minute.",
      "Add chicken and cook until browned.",
      "Add tomatoes and coconut milk, simmer until chicken is cooked through.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["Indian", "Curry", "Main Course"],
  },
  {
    recipe_id: 3,
    recipe_name: "Caesar Salad",
    description: "A fresh Caesar salad with crunchy croutons.",
    prep_time: "10 mins",
    cook_time: "0 mins",
    total_time: "10 mins",
    servings: 2,
    ingredients: [
      "Romaine Lettuce",
      "Caesar Dressing",
      "Croutons",
      "Parmesan Cheese",
    ],
    instructions: [
      "Chop the lettuce.",
      "Toss the lettuce with Caesar dressing.",
      "Add croutons and grated Parmesan cheese.",
      "Serve immediately.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["Salad", "Appetizer", "Healthy"],
  },
  {
    recipe_id: 4,
    recipe_name: "Beef Tacos",
    description: "Mexican beef tacos with toppings.",
    prep_time: "15 mins",
    cook_time: "10 mins",
    total_time: "25 mins",
    servings: 4,
    ingredients: [
      "Ground Beef",
      "Taco Seasoning",
      "Tortillas",
      "Cheese",
      "Lettuce",
      "Sour Cream",
      "Salsa",
    ],
    instructions: [
      "Cook ground beef with taco seasoning.",
      "Warm the tortillas.",
      "Assemble tacos with beef and your favorite toppings.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["Mexican", "Main Course", "Tacos"],
  },
  {
    recipe_id: 5,
    recipe_name: "Margherita Pizza",
    description: "A simple and delicious Margherita pizza.",
    prep_time: "15 mins",
    cook_time: "20 mins",
    total_time: "35 mins",
    servings: 2,
    ingredients: [
      "Pizza Dough",
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Basil Leaves",
      "Olive Oil",
    ],
    instructions: [
      "Spread tomato sauce on pizza dough.",
      "Top with mozzarella and fresh basil.",
      "Bake in a hot oven until the crust is golden and cheese melts.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["Italian", "Pizza", "Main Course"],
  },
  {
    recipe_id: 6,
    recipe_name: "Butter Chicken",
    description: "A rich and creamy Indian butter chicken.",
    prep_time: "15 mins",
    cook_time: "30 mins",
    total_time: "45 mins",
    servings: 4,
    ingredients: [
      "Chicken",
      "Butter",
      "Tomato Paste",
      "Cream",
      "Spices",
      "Ginger",
      "Garlic",
    ],
    instructions: [
      "Marinate the chicken with spices.",
      "Cook chicken in butter until browned.",
      "Add tomato paste and cream, simmer until the chicken is fully cooked.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["Indian", "Curry", "Main Course"],
  },
  {
    recipe_id: 7,
    recipe_name: "Chocolate Chip Cookies",
    description: "Soft and chewy chocolate chip cookies.",
    prep_time: "15 mins",
    cook_time: "12 mins",
    total_time: "27 mins",
    servings: "24 cookies",
    ingredients: [
      "Flour",
      "Butter",
      "Sugar",
      "Chocolate Chips",
      "Eggs",
      "Vanilla Extract",
      "Baking Soda",
    ],
    instructions: [
      "Mix butter and sugar until creamy.",
      "Add eggs and vanilla, then dry ingredients.",
      "Stir in chocolate chips and bake until golden brown.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["Dessert", "Baking", "Cookies"],
  },
  {
    recipe_id: 8,
    recipe_name: "French Onion Soup",
    description: "A rich and savory French onion soup.",
    prep_time: "20 mins",
    cook_time: "40 mins",
    total_time: "1 hour",
    servings: 4,
    ingredients: [
      "Onions",
      "Beef Broth",
      "Butter",
      "Gruyère Cheese",
      "Baguette",
    ],
    instructions: [
      "Caramelize onions in butter.",
      "Add beef broth and simmer.",
      "Top with toasted baguette slices and melted Gruyère cheese.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["French", "Soup", "Appetizer"],
  },
  {
    recipe_id: 9,
    recipe_name: "Pad Thai",
    description: "A flavorful and popular Thai noodle dish.",
    prep_time: "15 mins",
    cook_time: "15 mins",
    total_time: "30 mins",
    servings: 4,
    ingredients: [
      "Rice Noodles",
      "Shrimp or Chicken",
      "Peanuts",
      "Bean Sprouts",
      "Eggs",
      "Tamarind Paste",
      "Fish Sauce",
      "Lime",
    ],
    instructions: [
      "Soak rice noodles until soft.",
      "Stir-fry chicken or shrimp with eggs and tamarind sauce.",
      "Toss with noodles, peanuts, and bean sprouts.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["Thai", "Noodles", "Main Course"],
  },
  {
    recipe_id: 10,
    recipe_name: "Eggplant Parmesan",
    description: "A delicious vegetarian eggplant Parmesan.",
    prep_time: "30 mins",
    cook_time: "40 mins",
    total_time: "1 hour 10 mins",
    servings: 4,
    ingredients: [
      "Eggplant",
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Parmesan Cheese",
      "Breadcrumbs",
    ],
    instructions: [
      "Slice and bread the eggplant.",
      "Layer with tomato sauce and cheese in a baking dish.",
      "Bake until golden and bubbly.",
    ],
    image_url: "https://marketplace.canva.com/EAFaFUz4aKo/2/0/1600w/canva-yellow-abstract-cooking-fire-free-logo-JmYWTjUsE-Q.jpg",
    categories: ["Italian", "Vegetarian", "Main Course"],
  },
];

export const categories = [
  "All",
  "Italian",
  "Pasta",
  "Main Course",
  "Appetizer",
  "Soup",
  "Vegetarian",
  "Dessert",
  "Baking",
  "Cookies",
  "Thai",
  "Noodles",
  "Indian",
  "Curry",
  "French",
  "Mexican",
  "Pizza",
  "Tacos",
  "Salad",
  "Healthy",
];
